builds:
  - id: proxier
    main: ./cmd/proxier/main.go
    dir: ./
    binary: proxier
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - builds:
      - proxier
    name_template: 'proxier_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

nfpms:
  - license: MIT License
    maintainer: ezeX Team <info@ezex.io>
    homepage: https://ezex.io
    bindir: /usr/local/bin
    description: A high-performance proxy that routes external endpoint requests to an origin server.  Let me know if you'd like to add more details, such as features, supported protocols, or use cases!
    formats:
      - deb
      - rpm

checksum:
  name_template: 'proxier_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
